name: CI/CD for WordPress

on:
  push:
    branches:
      - main                                    # Change to your branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2.4'                                             # Change to your desired PHP version

      - name: Install dependencies
        run: |
          sudo apt-get install -y libjpeg-dev libpng-dev                         # Install any necessary dependencies
          composer install --no-scripts --no-progress --prefer-dist
          npm ci
          npm run build

      - name: Run tests
        run: |
          ./vendor/bin/phpunit

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.127.0.0.1 }} # Set your server's host
          username: ${{ secrets.root }} # Set your server's username
          password: ${{ secrets.password }} # Set your server's password
          port: ${{ secrets.3306 }} # Set your server's SSH port
          script: |
            cd /path/to/wordpress
            git pull origin main
            # Additional deployment steps (e.g., cache clearing, database updates)
